<!-- BEGIN: Page Main-->
<div id="main">
    <div class="row">
        <div id="breadcrumbs-wrapper"
            data-image="<?php echo C_GLOBAL_APP_ASSET; ?>images/gallery/breadcrumb-bg.jpg">
            <!-- Search for small screen-->
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l6">
                        <h5 class="breadcrumbs-title mt-0 mb-0"><span>Member List</span></h5>
                    </div>
                    <div class="col s12 m6 l6 right-align-md">
                        <ol class="breadcrumbs mb-0">
                            <li class="breadcrumb-item"><a href="index">Home</a>
                            </li>
                            <li class="breadcrumb-item active">Member List
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="container">
                <!-- users list start -->
                <section class="users-list-wrapper section">
                    <div class="users-list-filter">
                        <div class="card-panel">
                            <div class="row">
                                <div class="col s12 m4 l3">
                                    <label for="search_username">Member Username</label>
                                    <div class="input-field">
                                        <input type="text" id="search_username" class="dt-search" data-dt-col="0">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_full_name">Member Full Name</label>
                                    <div class="input-field">
                                        <input type="text" id="search_full_name" class="dt-search" data-dt-col="1">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <a onclick="_dtSearch()" class="btn indigo waves-effect waves-light mr-2">Search</a>
                                    <a onclick="_resetDtSearch()" class="btn grey darken-3 waves-effect waves-light mr-2">Reset</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a class="waves-effect waves-light btn modal-trigger mb-2 mr-1" href="/user/user-add">Add New User</a>

                    <div class="users-list-table">
                        <div class="card">
                            <div class="card-content">
                                <!-- datatable start -->
                                <div class="responsive-table" style="overflow-x:auto;">
                                    <table id="list-datatable" class="table">
                                        <thead>
                                            <tr>
                                                <th>Member Username</th>
                                                <th>Member Full Name</th>
                                                <th>Group</th>
                                                <th>Contact Number</th>
                                                <th>Email</th>
                                                <th>DOB</th>
                                                <th>Edit</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- datatable ends -->
                            </div>
                        </div>
                    </div>


                </section>
                <!-- users list ends -->
            </div>
            <div class="content-overlay"></div>
        </div>
    </div>
</div>
<!-- END: Page Main-->


<script type="text/javascript">
    $(".ajaxLoader").show();

    $(document).ready(function() {
        $(".ajaxLoader").fadeOut();

        // datatable initialization
        usersTable = $("#list-datatable").DataTable({
            "lengthChange": false, // Hide "Show entries"
            "dom": 'lrtp', // Hide search bar
            "processing": true,
            "serverSide": true,
            'serverMethod': 'post',
            "ajax": {
                "url": '/user/user-list',
                "type": "POST",
                "dataFilter": function(data) {
                    checkStatus(data);
                    data = JSON.parse(data);
                    console.log(data);
                    if (data.status == false) {
                        alert(data.msg);
                        location.href = '/';
                        exit(0);
                    } else {
                        $(".ajaxLoader").fadeOut();
                        return JSON.stringify(data.data);
                    }
                }
            },
            "drawCallback": function(settings) {
            },
            "columns": [
                {
                    "data": "a.username",
                    render: function(data, type, row, meta) {
                        return row.username;
                    }
                },
                {
                    "data": "a.full_name",
                    render: function(data, type, row, meta) {
                        return row.full_name;
                    }
                },
                {
                    "orderable": false,
                    "data": "c.id",
                    render: function(data, type, row, meta) {
                        return row.group_name;
                    }
                },
                {
                    "orderable": false,
                    "data": "a.phone",
                    render: function(data, type, row, meta) {
                        return row.phone;
                    }
                },
                {
                    "orderable": false,
                    "data": "a.email",
                    render: function(data, type, row, meta) {
                        return row.email;
                    }
                },
                {
                    "orderable": false,
                    "data": "a.dob",
                    render: function(data, type, row, meta) {
                        return row.dob;
                    }
                },
                {
                    "orderable": false,
                    "searchable": false,
                    "data": "a.id",
                    render: function(data, type, row, meta) {
                        return `<a href="/user/user-add?item_id=${row.id}"><i class="material-icons">edit</i></a>`;
                    }
                },
                {
                    "orderable": false,
                    "searchable": false,
                    "data": "a.id",
                    render: function(data, type, row, meta) {
                        let checked = '';
                        let msg = 'Blocked';
                        if (row.status == 1) {
                            checked = 'checked';
                            msg = 'Active';
                        }
                        return `
                            <div class="switch mb-1">
                                <label>
                                    <input id="statusCheckbox" ${checked} type="checkbox" onchange="updateStatus(${row.id}, '${row.username}', this)"><span class="lever"></span>${msg}
                                </label>
                            </div>
                        `;
                    }
                },
            ],
            'columnDefs': [{
                className: "dt-center",
                targets: "_all"
            }],
            "order": [6, 'desc'],
        });

    });

    function updateStatus(item_id, name, obj) {

        if (confirm(`Are you confirm to update status?\nMember ID: ${item_id}\nUsername: ${name}`)) {    

            var param = {
                item_id: item_id
            };

            $(".ajaxLoader").show();
            $.post('/user/user-block', param, function(d) {
                checkStatus(d);
                $(".ajaxLoader").fadeOut();
                if (d.status) {
                    window.alert(d.msg);
                    location.href = '/user/user-list';
                } else {
                    window.alert(d.msg);
                    location.href = '/user/user-list';
                }
            }, 'json');
        } else {
            if ($(obj).is(':checked')) {
                $(obj).prop('checked',false);
            } else {
                $(obj).prop('checked',true);
            }
        }
    }
</script>
