<style type="text/css">
    .login-bg-1 {
        background-image: url('<?php echo C_GLOBAL_APP_ASSET; ?>images/login-bg.jpg');
    }
</style>

<div class="row">
    <div class="col s12">
        <div class="container">
            <div id="login-page" class="row">
                <div class="col s12 m6 l4 z-depth-4 card-panel border-radius-6 login-card bg-opacity-8">
                    <form class="login-form">
                        <div class="row">
                            <div class="input-field col s12">
                                <h5 style="text-align: center">Admin Sign in</h5>
                            </div>
                        </div>
                        <div class="row margin">
                            <div class="input-field col s12">
                                <i class="material-icons prefix pt-2">person_outline</i>
                                <input id="email" type="text">
                                <label for="email" class="center-align">Username</label>
                            </div>
                        </div>
                        <div class="row margin">
                            <div class="input-field col s12">
                                <i class="material-icons prefix pt-2">lock_outline</i>
                                <input id="password" type="password">
                                <label for="password">Password</label>
                            </div>
                        </div>
                        <!-- <div class="row">
                            <div class="col s12 m12 l12 ml-2 mt-1">
                                <p>
                                    <label>
                                        <input type="checkbox" />
                                        <span>Remember Me</span>
                                    </label>
                                </p>
                            </div>
                        </div> -->
                        <div class="row">
                            <div class="input-field col s12">
                                <a id="btnLogin" class="btn waves-effect waves-light border-round gradient-45deg-purple-deep-orange col s12">Login</a>
                            </div>
                        </div>
                        <div class="row">
                            <!-- <div class="input-field col s6 m6 l6">
                                <p class="margin medium-small"><a href="register">Register Now!</a></p>
                            </div> -->
                            <!-- <div class="input-field col s6 m6 l6">
                                <p class="margin right-align medium-small"><a href="user-forgot-password.html">Forgot password ?</a></p>
                            </div> -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="content-overlay"></div>
    </div>
</div>


<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/vendors.min.js"></script>
<!-- BEGIN VENDOR JS-->
<!-- BEGIN THEME  JS-->
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/plugins.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/search.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/custom/custom-script.js"></script>

<script type="text/javascript">
    $(".ajaxLoader").show();

    function callApi() {
        $(".resp").html("");
        $(".ajaxLoader").show();
        $("#btnLogin").addClass("disabled").attr("disabled", true);
        param = {
            email: $('#email').val().trim(),
            password: $('#password').val().trim()
        };
        $.post(apiUrl + '/auth/login', param, function(d) {
            console.log(d);
            $(".ajaxLoader").fadeOut();
            if (d.status) {
                alert(d.msg);
                location.href = '/user/user-list';
            } else {
                alert(d.msg);
                $("#btnLogin").removeClass("disabled").attr("disabled", false);
                // location.href = '/';
            }
        }, 'json');
    }

    $(document).ready(function() {
        $(".ajaxLoader").fadeOut();
        $("#btnLogin").click(function() {
            callApi();
        });
        $("#username,#password").unbind('keyup').keyup(function(e) {
            if (e.keyCode === 13) {
                $('#btnLogin').click();
                e.preventDefault();
                return;
            }
        });
    });
</script>