<link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/page-404.css">
<div class="row">
  <div class="col s12">
    <div class="container">
      <div class="section section-404 p-0 m-0 height-100vh">
        <div class="row">
          <!-- 404 -->
          <div class="col s12 center-align white">
            <img src="<?php echo C_GLOBAL_APP_ASSET; ?>images/gallery/error-2.png" class="bg-image-404" alt="">
            <h1 class="error-code m-0">404</h1>
            <h6 class="mb-2">BAD REQUEST</h6>
            <a class="btn waves-effect waves-light gradient-45deg-deep-purple-blue gradient-shadow mb-4" href="home">Back
              TO Home</a>
          </div>
        </div>
      </div>
    </div>
    <div class="content-overlay"></div>
  </div>
</div>