<?php
// $messenger = Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger');
$sess = new Zend_Session_Namespace('Zend_Auth');
?>
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">
    <title>Admin</title>
    <link rel="apple-touch-icon" href="<?php echo C_GLOBAL_IMG; ?>icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo C_GLOBAL_IMG; ?>icon.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/data-tables/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/data-tables/css/dataTables.checkboxes.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/select2/select2-materialize.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/flag-icon/css/flag-icon.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/quill/katex.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/quill/monokai-sublime.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/quill/quill.snow.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/quill/quill.bubble.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/chartist-js/chartist.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/chartist-js/chartist-plugin-tooltip.css">
    <!-- END: VENDOR CSS-->
    <!-- BEGIN: Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/dashboard-modern.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/themes/vertical-dark-menu-template/materialize.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/themes/vertical-dark-menu-template/style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/login.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/register.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/page-users.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/page-account-settings.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/pages/dashboard.css">
    <!-- END: Page Level CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_APP_ASSET; ?>css/custom/custom.css">
    <link rel="stylesheet" type="text/css" href="<?php echo C_GLOBAL_CSS; ?>daterangepicker.css">
    <!-- END: Custom CSS-->

    <script src="<?php echo C_GLOBAL_JS; ?>jquery-3.5.1.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
    <script type="text/javascript" src="<?php echo C_GLOBAL_JS ?>scripts.js"></script>
    <script type="text/javascript" src="<?php echo C_GLOBAL_JS ?>dt-search.js"></script>

</head>
<!-- END: Head-->

<!-- body class-->
<?php
if (isset($sess->user) && !empty($sess->user)) {
    echo '<body class="vertical-layout page-header-light vertical-menu-collapsible vertical-dark-menu preload-transitions 2-columns   " data-open="click" data-menu="vertical-dark-menu" data-col="2-columns">';
} else {
    echo '<body class="vertical-layout page-header-light vertical-menu-collapsible vertical-gradient-menu preload-transitions 1-column login-bg-1 blank-page blank-page" data-open="click" data-menu="vertical-gradient-menu" data-col="1-column">';
}
?>



<!-- after login -->
<?php
echo $this->partial("common/loader.phtml");
if (isset($sess->user) && !empty($sess->user)) {
    echo $this->partial("common/topbar.phtml");
    echo $this->partial("common/sidebar.phtml");
    echo $this->layout()->content;
    echo $this->partial("common/footer.phtml");
    // before login
} else {
    echo $this->layout()->content;
    echo $this->partial("common/footer.phtml");
} ?>
</body>

<script type="text/javascript">
    function IsJsonString(str) {
        try {
            JSON.parse(str);
        } catch (e) {
            return false;
        }
        return true;
    }

    // Check response status
    function checkStatus(data) {
        if (IsJsonString(data)) {
            data = JSON.parse(data);
        }

        if (typeof data.status === 'undefined') {
            alert('Return data error');
            location.href = '/';
            return;
        }
        if (data.status == false) {
            if (data.code == 100002) {
                alert('Please login and try again.');
                location.href = '/logout';
                exit(0);
            }
            if (data.code == 100001) {
                alert(data.msg);
                location.href = '/';
                exit(0);
            }
        }
        return;
    }
</script>


</html>