<!-- custom date range picker js, class name: search_date_range -->
<script type="text/javascript" src="<?php echo C_GLOBAL_JS ?>date-range.js"></script>

<!-- BEGIN: Page Main-->
<div id="main">
    <div class="row">
        <div id="breadcrumbs-wrapper"
            data-image="<?php echo C_GLOBAL_APP_ASSET; ?>images/gallery/breadcrumb-bg.jpg">
            <!-- Search for small screen-->
            <div class="container">
                <div class="row">
                    <div class="col s12 m6 l6">
                        <h5 class="breadcrumbs-title mt-0 mb-0"><span>Promotion History</span></h5>
                    </div>
                    <div class="col s12 m6 l6 right-align-md">
                        <ol class="breadcrumbs mb-0">
                            <li class="breadcrumb-item"><a href="index">Home</a>
                            </li>
                            <li class="breadcrumb-item active">Promotion History
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="container">
                <!-- users list start -->
                <section class="users-list-wrapper section">
                    <div class="users-list-filter">
                        <div class="card-panel">
                            <div class="row">
                                <div class="col s12 m4 l3">
                                    <label for="search_date_range">Search Date</label>
                                    <div class="input-field">
                                        <input type="text" name="dates" id="search_date_range" value="">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_admin">Added By</label>
                                    <div class="input-field">
                                        <input type="text" id="search_admin" class="dt-search" data-dt-col="0">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_name">Username</label>
                                    <div class="input-field">
                                        <input type="text" id="search_name" class="dt-search" data-dt-col="1">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_fullname">Member Full Name</label>
                                    <div class="input-field">
                                        <input type="text" id="search_fullname" class="dt-search" data-dt-col="2">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_amount">Amount</label>
                                    <div class="input-field">
                                        <input type="text" id="search_amount" class="dt-search" data-dt-col="3">
                                    </div>
                                </div>
                                <div class="col s12 m4 l3">
                                    <label for="search_remark">Remark</label>
                                    <div class="input-field">
                                        <input type="text" id="search_remark" class="dt-search" data-dt-col="5">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12">
                                    <a onclick="_dtSearch()" class="btn indigo waves-effect waves-light mr-2">Search</a>
                                    <a onclick="_resetDtSearch()" class="btn grey darken-3 waves-effect waves-light mr-2">Reset</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="users-list-table">
                        <div class="card">
                            <div class="card-content">
                                <!-- datatable start -->
                                <div class="responsive-table" style="overflow-x:auto;">
                                    <table id="list-datatable" class="table">
                                        <thead>
                                            <tr>
                                                <th>Added By</th>
                                                <th>Username</th>
                                                <th>Member Full Name</th>
                                                <th>Amount</th>
                                                <th>Date</th>
                                                <!-- <th>Status</th> -->
                                                <th>Remark</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                        <tfoot style="background: #C5C5C5; color: #000075;">
                                            <tr>
                                                <td colspan="3">Total</td>
                                                <td id="page_total_amount">0</td>
                                                <td colspan="2"></td>
                                            </tr>
                                            <tr>
                                                <td id="total_count" colspan="3" class="dt-center">Total Records: 0</td>
                                                <td id="total_amount" class="dt-center">0</td>
                                                <td colspan="2" class="dt-center"></td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- datatable ends -->
                            </div>
                        </div>
                    </div>


                </section>
                <!-- users list ends -->
            </div>
            <div class="content-overlay"></div>
        </div>
    </div>
</div>
<!-- END: Page Main-->


<script type="text/javascript">
    $(".ajaxLoader").show();
    var page_total_amount = 0;

    $(document).ready(function() {
        $(".ajaxLoader").fadeOut();
        _init();

        // datatable initialization
        usersTable = $("#list-datatable").DataTable({
            "lengthChange": true, // Hide "Show entries"
            "dom": 'lrtp', // Hide search bar
            "processing": true,
            "serverSide": true,
            'serverMethod': 'post',
            "ajax": {
                "url": '/promo/promo-list',
                "type": "POST",
                "dataFilter": function(data) {
                    // checkStatus(data);

                    // reset
                    page_total_amount = 0;

                    data = JSON.parse(data);
                    console.log(data);
                    if (data.status == false) {
                        alert(data.msg);
                        location.href = '/';
                        exit(0);
                    } else {
                        $(".ajaxLoader").fadeOut();
                        return JSON.stringify(data.data);
                    }
                }
            },
            "drawCallback": function(settings) {
                $('#page_total_amount').html(page_total_amount);
            },
            "columns": [
                {
                    "searchable": false,
                    "orderable": false,
                    "data": "a.aid",
                    render: function(data, type, row, meta) {
                        return row.admin_username;
                    }
                },
                {
                    "orderable": false,
                    "data": "b.username",
                    render: function(data, type, row, meta) {
                        return row.username;
                    }
                },
                {
                    "orderable": false,
                    "data": "b.full_name",
                    render: function(data, type, row, meta) {
                        return row.full_name;
                    }
                },
                {
                    "data": "a.amount",
                    render: function(data, type, row, meta) {
                        let v = Number(row.amount);
                        page_total_amount += v;
                        return v;
                    }
                },
                {
                    "data": "a.created_at",
                    render: function(data, type, row, meta) {
                        return row.created_at;
                    }
                },
                // {
                //     "searchable": false,
                //     "orderable": false,
                //     "data": "a.id",
                //     render: function(data, type, row, meta) {
                //         let checked = '';
                //         let msg = 'Inactive';
                //         if (row.status == 1) {
                //             checked = 'checked';
                //             msg = 'Approved';
                //         }
                //         return `
                //             <div class="switch mb-1">
                //                 <label>
                //                     <input ${checked} type="checkbox" onchange="updateStatus(${row.id}, this)"><span class="lever"></span>${msg}
                //                 </label>
                //             </div>
                //         `;
                //     }
                // },
                {
                    "orderable": false,
                    "data": "a.remark",
                    render: function(data, type, row, meta) {
                        return row.remark;
                    }
                },
            ],
            'columnDefs': [{
                className: "dt-center",
                targets: "_all"
            }],
            "order": [4, 'desc'],
        });

        $('#search_date_range').on("change", function() {
            usersTable.ajax.url(`/promo/promo-list?start_date=${_start_date}&end_date=${_end_date}`).load();
        })

    });

    function _init(item_id) {
        var param = {
            not_pagin: 1
        };

        $.post('/promo/promo-report', param, function(d) {
            // checkStatus(d);
            // console.log(d);
            if (d.status) {
                if (typeof d.data !== 'undefined') {
                    $('#total_count').html(`Total Records: ${d.data.total_count}`);
                    $('#total_amount').html(d.data.total_amount);
                }
            } else {
                // window.alert(d.msg);
            }
        }, 'json');
    }

    function updateStatus(item_id, obj) {
        if (confirm('Are you confirm to update status?')) {
            var param = {
                item_id: item_id
            };

            $(".ajaxLoader").show();
            $.post('/promo/promo-block', param, function(d) {
                checkStatus(d);
                if (d.status) {
                    // window.alert(d.msg);
                    location.href = '/promo/promo-list';
                } else {
                    $(".ajaxLoader").fadeOut();
                    window.alert(d.msg);
                    location.href = '/promo/promo-list';
                }
            }, 'json');
        } else {
            if ($(obj).is(':checked')) {
                $(obj).prop('checked',false);
            } else {
                $(obj).prop('checked',true);
            }
        }
    }


</script>
