<footer class="page-footer footer footer-static footer-light navbar-border navbar-shadow">
    <div class="footer-copyright">
        <div class="container"><span>&copy; 2022 <a href="http://zend_base.com" target="_blank">zend_base SDN. BHD.</a> All rights reserved.</span></div>
    </div>
</footer>



<!-- BEGIN VENDOR JS-->
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/vendors.min.js"></script>
<!-- BEGIN VENDOR JS-->
<!-- BEGIN THEME  JS-->
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/plugins.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/search.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/custom/custom-script.js"></script>

<script src="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/select2/select2.full.min.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/scripts/form-editor.js"></script>
<!-- END THEME  JS-->

<!-- BEGIN PAGE VENDOR JS-->
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/data-tables/js/jquery.dataTables.js"></script>
<!-- <script src="<?php echo C_GLOBAL_APP_ASSET; ?>vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js"></script> -->
<!-- END PAGE VENDOR JS-->

<!-- BEGIN PAGE LEVEL JS-->
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/scripts/page-users.js"></script>
<script src="<?php echo C_GLOBAL_APP_ASSET; ?>js/scripts/advance-ui-modals.js"></script>
<!-- END PAGE LEVEL JS-->

<script type="text/javascript" src="<?php echo C_GLOBAL_JS ?>moment.min.js"></script>
<script type="text/javascript" src="<?php echo C_GLOBAL_JS ?>daterangepicker.min.js"></script>